# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/user/Desktop/KD240/01_vivado/kd240_ecat_lan9252/kd240_ecat_lan9252.srcs/sources_1/bd/kd240_ecat_bd/ip/kd240_ecat_bd_heater_axi_0_0/kd240_ecat_bd_heater_axi_0_0.xci
# IP: The module: 'kd240_ecat_bd_heater_axi_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/user/Desktop/KD240/01_vivado/kd240_ecat_lan9252/kd240_ecat_lan9252.gen/sources_1/bd/kd240_ecat_bd/ip/kd240_ecat_bd_heater_axi_0_0/src/fp_add_1/fp_add.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fp_add || ORIG_REF_NAME==fp_add} -quiet] -quiet

# IP: c:/Users/user/Desktop/KD240/01_vivado/kd240_ecat_lan9252/kd240_ecat_lan9252.gen/sources_1/bd/kd240_ecat_bd/ip/kd240_ecat_bd_heater_axi_0_0/src/fp_mult_1/fp_mult.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fp_mult || ORIG_REF_NAME==fp_mult} -quiet] -quiet

# IP: C:/Users/user/Desktop/KD240/01_vivado/kd240_ecat_lan9252/kd240_ecat_lan9252.srcs/sources_1/bd/kd240_ecat_bd/ip/kd240_ecat_bd_heater_axi_0_0/kd240_ecat_bd_heater_axi_0_0.xci
# IP: The module: 'kd240_ecat_bd_heater_axi_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/user/Desktop/KD240/01_vivado/kd240_ecat_lan9252/kd240_ecat_lan9252.gen/sources_1/bd/kd240_ecat_bd/ip/kd240_ecat_bd_heater_axi_0_0/src/fp_add_1/fp_add.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fp_add || ORIG_REF_NAME==fp_add} -quiet] -quiet

# IP: c:/Users/user/Desktop/KD240/01_vivado/kd240_ecat_lan9252/kd240_ecat_lan9252.gen/sources_1/bd/kd240_ecat_bd/ip/kd240_ecat_bd_heater_axi_0_0/src/fp_mult_1/fp_mult.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fp_mult || ORIG_REF_NAME==fp_mult} -quiet] -quiet
