# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/kd240_j2_pmod_lan9252.xdc

# Block Designs: bd/kd240_ecat_bd/kd240_ecat_bd.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kd240_ecat_bd || ORIG_REF_NAME==kd240_ecat_bd} -quiet] -quiet

# IP: bd/kd240_ecat_bd/ip/kd240_ecat_bd_zynq_ultra_ps_e_0_0/kd240_ecat_bd_zynq_ultra_ps_e_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kd240_ecat_bd_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==kd240_ecat_bd_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: bd/kd240_ecat_bd/ip/kd240_ecat_bd_axi_quad_spi_0_0/kd240_ecat_bd_axi_quad_spi_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kd240_ecat_bd_axi_quad_spi_0_0 || ORIG_REF_NAME==kd240_ecat_bd_axi_quad_spi_0_0} -quiet] -quiet

# IP: bd/kd240_ecat_bd/ip/kd240_ecat_bd_axi_smc_0/kd240_ecat_bd_axi_smc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kd240_ecat_bd_axi_smc_0 || ORIG_REF_NAME==kd240_ecat_bd_axi_smc_0} -quiet] -quiet

# IP: bd/kd240_ecat_bd/ip/kd240_ecat_bd_rst_ps8_0_99M_0/kd240_ecat_bd_rst_ps8_0_99M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kd240_ecat_bd_rst_ps8_0_99M_0 || ORIG_REF_NAME==kd240_ecat_bd_rst_ps8_0_99M_0} -quiet] -quiet

# IP: bd/kd240_ecat_bd/ip/kd240_ecat_bd_ecat_pl_if_0_0/kd240_ecat_bd_ecat_pl_if_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kd240_ecat_bd_ecat_pl_if_0_0 || ORIG_REF_NAME==kd240_ecat_bd_ecat_pl_if_0_0} -quiet] -quiet

# IP: bd/kd240_ecat_bd/ip/kd240_ecat_bd_xlconcat_0_0/kd240_ecat_bd_xlconcat_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kd240_ecat_bd_xlconcat_0_0 || ORIG_REF_NAME==kd240_ecat_bd_xlconcat_0_0} -quiet] -quiet

# IP: bd/kd240_ecat_bd/ip/kd240_ecat_bd_heater_axi_0_0/kd240_ecat_bd_heater_axi_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kd240_ecat_bd_heater_axi_0_0 || ORIG_REF_NAME==kd240_ecat_bd_heater_axi_0_0} -quiet] -quiet

# XDC: c:/Users/user/Desktop/KD240/01_vivado/kd240_ecat_lan9252/kd240_ecat_lan9252.gen/sources_1/bd/kd240_ecat_bd/kd240_ecat_bd_ooc.xdc
