domain_path: C:\Users\user\Desktop\KD240\02_vitis\kd240_ecat_platform\export\kd240_ecat_platform\sw\standalone_psu_cortexr5_0
app_src_dir: C:\AMDDesignTools\2025.2\Vitis\data\embeddedsw\lib\sw_apps\empty_application
template: empty_application
lang: c
