# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/user/Desktop/KD240/01_vivado/kd240_ecat_lan9252/kd240_ecat_lan9252.srcs/sources_1/bd/kd240_ecat_bd/ip/kd240_ecat_bd_axi_smc_0/kd240_ecat_bd_axi_smc_0.xci
# IP: The module: 'kd240_ecat_bd_axi_smc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/Users/user/Desktop/KD240/01_vivado/kd240_ecat_lan9252/kd240_ecat_lan9252.gen/sources_1/bd/kd240_ecat_bd/ip/kd240_ecat_bd_axi_smc_0/bd_0/bd_6104.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/user/Desktop/KD240/01_vivado/kd240_ecat_lan9252/kd240_ecat_lan9252.gen/sources_1/bd/kd240_ecat_bd/ip/kd240_ecat_bd_axi_smc_0/bd_0/ip/ip_1/bd_6104_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/user/Desktop/KD240/01_vivado/kd240_ecat_lan9252/kd240_ecat_lan9252.gen/sources_1/bd/kd240_ecat_bd/ip/kd240_ecat_bd_axi_smc_0/bd_0/ip/ip_2/bd_6104_arinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/user/Desktop/KD240/01_vivado/kd240_ecat_lan9252/kd240_ecat_lan9252.gen/sources_1/bd/kd240_ecat_bd/ip/kd240_ecat_bd_axi_smc_0/bd_0/ip/ip_3/bd_6104_rinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/user/Desktop/KD240/01_vivado/kd240_ecat_lan9252/kd240_ecat_lan9252.gen/sources_1/bd/kd240_ecat_bd/ip/kd240_ecat_bd_axi_smc_0/bd_0/ip/ip_4/bd_6104_awinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/user/Desktop/KD240/01_vivado/kd240_ecat_lan9252/kd240_ecat_lan9252.gen/sources_1/bd/kd240_ecat_bd/ip/kd240_ecat_bd_axi_smc_0/bd_0/ip/ip_5/bd_6104_winsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/user/Desktop/KD240/01_vivado/kd240_ecat_lan9252/kd240_ecat_lan9252.gen/sources_1/bd/kd240_ecat_bd/ip/kd240_ecat_bd_axi_smc_0/bd_0/ip/ip_6/bd_6104_binsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/user/Desktop/KD240/01_vivado/kd240_ecat_lan9252/kd240_ecat_lan9252.gen/sources_1/bd/kd240_ecat_bd/ip/kd240_ecat_bd_axi_smc_0/bd_0/ip/ip_7/bd_6104_aroutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/user/Desktop/KD240/01_vivado/kd240_ecat_lan9252/kd240_ecat_lan9252.gen/sources_1/bd/kd240_ecat_bd/ip/kd240_ecat_bd_axi_smc_0/bd_0/ip/ip_8/bd_6104_routsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/user/Desktop/KD240/01_vivado/kd240_ecat_lan9252/kd240_ecat_lan9252.gen/sources_1/bd/kd240_ecat_bd/ip/kd240_ecat_bd_axi_smc_0/bd_0/ip/ip_9/bd_6104_awoutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/user/Desktop/KD240/01_vivado/kd240_ecat_lan9252/kd240_ecat_lan9252.gen/sources_1/bd/kd240_ecat_bd/ip/kd240_ecat_bd_axi_smc_0/bd_0/ip/ip_10/bd_6104_woutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/user/Desktop/KD240/01_vivado/kd240_ecat_lan9252/kd240_ecat_lan9252.gen/sources_1/bd/kd240_ecat_bd/ip/kd240_ecat_bd_axi_smc_0/bd_0/ip/ip_11/bd_6104_boutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/user/Desktop/KD240/01_vivado/kd240_ecat_lan9252/kd240_ecat_lan9252.gen/sources_1/bd/kd240_ecat_bd/ip/kd240_ecat_bd_axi_smc_0/bd_0/ip/ip_12/bd_6104_arni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/user/Desktop/KD240/01_vivado/kd240_ecat_lan9252/kd240_ecat_lan9252.gen/sources_1/bd/kd240_ecat_bd/ip/kd240_ecat_bd_axi_smc_0/bd_0/ip/ip_13/bd_6104_rni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/user/Desktop/KD240/01_vivado/kd240_ecat_lan9252/kd240_ecat_lan9252.gen/sources_1/bd/kd240_ecat_bd/ip/kd240_ecat_bd_axi_smc_0/bd_0/ip/ip_14/bd_6104_awni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/user/Desktop/KD240/01_vivado/kd240_ecat_lan9252/kd240_ecat_lan9252.gen/sources_1/bd/kd240_ecat_bd/ip/kd240_ecat_bd_axi_smc_0/bd_0/ip/ip_15/bd_6104_wni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/user/Desktop/KD240/01_vivado/kd240_ecat_lan9252/kd240_ecat_lan9252.gen/sources_1/bd/kd240_ecat_bd/ip/kd240_ecat_bd_axi_smc_0/bd_0/ip/ip_16/bd_6104_bni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/user/Desktop/KD240/01_vivado/kd240_ecat_lan9252/kd240_ecat_lan9252.gen/sources_1/bd/kd240_ecat_bd/ip/kd240_ecat_bd_axi_smc_0/bd_0/ip/ip_17/bd_6104_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/user/Desktop/KD240/01_vivado/kd240_ecat_lan9252/kd240_ecat_lan9252.gen/sources_1/bd/kd240_ecat_bd/ip/kd240_ecat_bd_axi_smc_0/bd_0/ip/ip_18/bd_6104_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/user/Desktop/KD240/01_vivado/kd240_ecat_lan9252/kd240_ecat_lan9252.gen/sources_1/bd/kd240_ecat_bd/ip/kd240_ecat_bd_axi_smc_0/bd_0/ip/ip_19/bd_6104_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/user/Desktop/KD240/01_vivado/kd240_ecat_lan9252/kd240_ecat_lan9252.gen/sources_1/bd/kd240_ecat_bd/ip/kd240_ecat_bd_axi_smc_0/bd_0/ip/ip_20/bd_6104_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/user/Desktop/KD240/01_vivado/kd240_ecat_lan9252/kd240_ecat_lan9252.gen/sources_1/bd/kd240_ecat_bd/ip/kd240_ecat_bd_axi_smc_0/bd_0/ip/ip_21/bd_6104_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/user/Desktop/KD240/01_vivado/kd240_ecat_lan9252/kd240_ecat_lan9252.gen/sources_1/bd/kd240_ecat_bd/ip/kd240_ecat_bd_axi_smc_0/bd_0/ip/ip_22/bd_6104_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/user/Desktop/KD240/01_vivado/kd240_ecat_lan9252/kd240_ecat_lan9252.gen/sources_1/bd/kd240_ecat_bd/ip/kd240_ecat_bd_axi_smc_0/bd_0/ip/ip_23/bd_6104_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/user/Desktop/KD240/01_vivado/kd240_ecat_lan9252/kd240_ecat_lan9252.gen/sources_1/bd/kd240_ecat_bd/ip/kd240_ecat_bd_axi_smc_0/bd_0/ip/ip_24/bd_6104_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/user/Desktop/KD240/01_vivado/kd240_ecat_lan9252/kd240_ecat_lan9252.gen/sources_1/bd/kd240_ecat_bd/ip/kd240_ecat_bd_axi_smc_0/bd_0/ip/ip_25/bd_6104_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/user/Desktop/KD240/01_vivado/kd240_ecat_lan9252/kd240_ecat_lan9252.gen/sources_1/bd/kd240_ecat_bd/ip/kd240_ecat_bd_axi_smc_0/bd_0/ip/ip_26/bd_6104_s01mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/user/Desktop/KD240/01_vivado/kd240_ecat_lan9252/kd240_ecat_lan9252.gen/sources_1/bd/kd240_ecat_bd/ip/kd240_ecat_bd_axi_smc_0/bd_0/ip/ip_27/bd_6104_s01tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/user/Desktop/KD240/01_vivado/kd240_ecat_lan9252/kd240_ecat_lan9252.gen/sources_1/bd/kd240_ecat_bd/ip/kd240_ecat_bd_axi_smc_0/bd_0/ip/ip_28/bd_6104_s01sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/user/Desktop/KD240/01_vivado/kd240_ecat_lan9252/kd240_ecat_lan9252.gen/sources_1/bd/kd240_ecat_bd/ip/kd240_ecat_bd_axi_smc_0/bd_0/ip/ip_29/bd_6104_s01a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/user/Desktop/KD240/01_vivado/kd240_ecat_lan9252/kd240_ecat_lan9252.gen/sources_1/bd/kd240_ecat_bd/ip/kd240_ecat_bd_axi_smc_0/bd_0/ip/ip_30/bd_6104_sarn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/user/Desktop/KD240/01_vivado/kd240_ecat_lan9252/kd240_ecat_lan9252.gen/sources_1/bd/kd240_ecat_bd/ip/kd240_ecat_bd_axi_smc_0/bd_0/ip/ip_31/bd_6104_srn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/user/Desktop/KD240/01_vivado/kd240_ecat_lan9252/kd240_ecat_lan9252.gen/sources_1/bd/kd240_ecat_bd/ip/kd240_ecat_bd_axi_smc_0/bd_0/ip/ip_32/bd_6104_sawn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/user/Desktop/KD240/01_vivado/kd240_ecat_lan9252/kd240_ecat_lan9252.gen/sources_1/bd/kd240_ecat_bd/ip/kd240_ecat_bd_axi_smc_0/bd_0/ip/ip_33/bd_6104_swn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/user/Desktop/KD240/01_vivado/kd240_ecat_lan9252/kd240_ecat_lan9252.gen/sources_1/bd/kd240_ecat_bd/ip/kd240_ecat_bd_axi_smc_0/bd_0/ip/ip_34/bd_6104_sbn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/user/Desktop/KD240/01_vivado/kd240_ecat_lan9252/kd240_ecat_lan9252.gen/sources_1/bd/kd240_ecat_bd/ip/kd240_ecat_bd_axi_smc_0/bd_0/ip/ip_35/bd_6104_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/user/Desktop/KD240/01_vivado/kd240_ecat_lan9252/kd240_ecat_lan9252.gen/sources_1/bd/kd240_ecat_bd/ip/kd240_ecat_bd_axi_smc_0/bd_0/ip/ip_36/bd_6104_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/user/Desktop/KD240/01_vivado/kd240_ecat_lan9252/kd240_ecat_lan9252.gen/sources_1/bd/kd240_ecat_bd/ip/kd240_ecat_bd_axi_smc_0/bd_0/ip/ip_37/bd_6104_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/user/Desktop/KD240/01_vivado/kd240_ecat_lan9252/kd240_ecat_lan9252.gen/sources_1/bd/kd240_ecat_bd/ip/kd240_ecat_bd_axi_smc_0/bd_0/ip/ip_38/bd_6104_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/user/Desktop/KD240/01_vivado/kd240_ecat_lan9252/kd240_ecat_lan9252.gen/sources_1/bd/kd240_ecat_bd/ip/kd240_ecat_bd_axi_smc_0/bd_0/ip/ip_39/bd_6104_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/user/Desktop/KD240/01_vivado/kd240_ecat_lan9252/kd240_ecat_lan9252.gen/sources_1/bd/kd240_ecat_bd/ip/kd240_ecat_bd_axi_smc_0/bd_0/ip/ip_40/bd_6104_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/user/Desktop/KD240/01_vivado/kd240_ecat_lan9252/kd240_ecat_lan9252.gen/sources_1/bd/kd240_ecat_bd/ip/kd240_ecat_bd_axi_smc_0/bd_0/ip/ip_41/bd_6104_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/user/Desktop/KD240/01_vivado/kd240_ecat_lan9252/kd240_ecat_lan9252.gen/sources_1/bd/kd240_ecat_bd/ip/kd240_ecat_bd_axi_smc_0/bd_0/ip/ip_42/bd_6104_m01s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/user/Desktop/KD240/01_vivado/kd240_ecat_lan9252/kd240_ecat_lan9252.gen/sources_1/bd/kd240_ecat_bd/ip/kd240_ecat_bd_axi_smc_0/bd_0/ip/ip_43/bd_6104_m01arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/user/Desktop/KD240/01_vivado/kd240_ecat_lan9252/kd240_ecat_lan9252.gen/sources_1/bd/kd240_ecat_bd/ip/kd240_ecat_bd_axi_smc_0/bd_0/ip/ip_44/bd_6104_m01rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/user/Desktop/KD240/01_vivado/kd240_ecat_lan9252/kd240_ecat_lan9252.gen/sources_1/bd/kd240_ecat_bd/ip/kd240_ecat_bd_axi_smc_0/bd_0/ip/ip_45/bd_6104_m01awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/user/Desktop/KD240/01_vivado/kd240_ecat_lan9252/kd240_ecat_lan9252.gen/sources_1/bd/kd240_ecat_bd/ip/kd240_ecat_bd_axi_smc_0/bd_0/ip/ip_46/bd_6104_m01wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/user/Desktop/KD240/01_vivado/kd240_ecat_lan9252/kd240_ecat_lan9252.gen/sources_1/bd/kd240_ecat_bd/ip/kd240_ecat_bd_axi_smc_0/bd_0/ip/ip_47/bd_6104_m01bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/user/Desktop/KD240/01_vivado/kd240_ecat_lan9252/kd240_ecat_lan9252.gen/sources_1/bd/kd240_ecat_bd/ip/kd240_ecat_bd_axi_smc_0/bd_0/ip/ip_48/bd_6104_m01e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/user/Desktop/KD240/01_vivado/kd240_ecat_lan9252/kd240_ecat_lan9252.gen/sources_1/bd/kd240_ecat_bd/ip/kd240_ecat_bd_axi_smc_0/bd_0/ip/ip_49/bd_6104_m02s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/user/Desktop/KD240/01_vivado/kd240_ecat_lan9252/kd240_ecat_lan9252.gen/sources_1/bd/kd240_ecat_bd/ip/kd240_ecat_bd_axi_smc_0/bd_0/ip/ip_50/bd_6104_m02arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/user/Desktop/KD240/01_vivado/kd240_ecat_lan9252/kd240_ecat_lan9252.gen/sources_1/bd/kd240_ecat_bd/ip/kd240_ecat_bd_axi_smc_0/bd_0/ip/ip_51/bd_6104_m02rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/user/Desktop/KD240/01_vivado/kd240_ecat_lan9252/kd240_ecat_lan9252.gen/sources_1/bd/kd240_ecat_bd/ip/kd240_ecat_bd_axi_smc_0/bd_0/ip/ip_52/bd_6104_m02awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/user/Desktop/KD240/01_vivado/kd240_ecat_lan9252/kd240_ecat_lan9252.gen/sources_1/bd/kd240_ecat_bd/ip/kd240_ecat_bd_axi_smc_0/bd_0/ip/ip_53/bd_6104_m02wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/user/Desktop/KD240/01_vivado/kd240_ecat_lan9252/kd240_ecat_lan9252.gen/sources_1/bd/kd240_ecat_bd/ip/kd240_ecat_bd_axi_smc_0/bd_0/ip/ip_54/bd_6104_m02bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/user/Desktop/KD240/01_vivado/kd240_ecat_lan9252/kd240_ecat_lan9252.gen/sources_1/bd/kd240_ecat_bd/ip/kd240_ecat_bd_axi_smc_0/bd_0/ip/ip_55/bd_6104_m02e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: c:/Users/user/Desktop/KD240/01_vivado/kd240_ecat_lan9252/kd240_ecat_lan9252.gen/sources_1/bd/kd240_ecat_bd/ip/kd240_ecat_bd_axi_smc_0/bd_0/ip/ip_1/bd_6104_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/user/Desktop/KD240/01_vivado/kd240_ecat_lan9252/kd240_ecat_lan9252.gen/sources_1/bd/kd240_ecat_bd/ip/kd240_ecat_bd_axi_smc_0/bd_0/ip/ip_2/bd_6104_arinsw_0_ooc.xdc

# XDC: c:/Users/user/Desktop/KD240/01_vivado/kd240_ecat_lan9252/kd240_ecat_lan9252.gen/sources_1/bd/kd240_ecat_bd/ip/kd240_ecat_bd_axi_smc_0/bd_0/ip/ip_3/bd_6104_rinsw_0_ooc.xdc

# XDC: c:/Users/user/Desktop/KD240/01_vivado/kd240_ecat_lan9252/kd240_ecat_lan9252.gen/sources_1/bd/kd240_ecat_bd/ip/kd240_ecat_bd_axi_smc_0/bd_0/ip/ip_4/bd_6104_awinsw_0_ooc.xdc

# XDC: c:/Users/user/Desktop/KD240/01_vivado/kd240_ecat_lan9252/kd240_ecat_lan9252.gen/sources_1/bd/kd240_ecat_bd/ip/kd240_ecat_bd_axi_smc_0/bd_0/ip/ip_5/bd_6104_winsw_0_ooc.xdc

# XDC: c:/Users/user/Desktop/KD240/01_vivado/kd240_ecat_lan9252/kd240_ecat_lan9252.gen/sources_1/bd/kd240_ecat_bd/ip/kd240_ecat_bd_axi_smc_0/bd_0/ip/ip_6/bd_6104_binsw_0_ooc.xdc

# XDC: c:/Users/user/Desktop/KD240/01_vivado/kd240_ecat_lan9252/kd240_ecat_lan9252.gen/sources_1/bd/kd240_ecat_bd/ip/kd240_ecat_bd_axi_smc_0/bd_0/ip/ip_7/bd_6104_aroutsw_0_ooc.xdc

# XDC: c:/Users/user/Desktop/KD240/01_vivado/kd240_ecat_lan9252/kd240_ecat_lan9252.gen/sources_1/bd/kd240_ecat_bd/ip/kd240_ecat_bd_axi_smc_0/bd_0/ip/ip_8/bd_6104_routsw_0_ooc.xdc

# XDC: c:/Users/user/Desktop/KD240/01_vivado/kd240_ecat_lan9252/kd240_ecat_lan9252.gen/sources_1/bd/kd240_ecat_bd/ip/kd240_ecat_bd_axi_smc_0/bd_0/ip/ip_9/bd_6104_awoutsw_0_ooc.xdc

# XDC: c:/Users/user/Desktop/KD240/01_vivado/kd240_ecat_lan9252/kd240_ecat_lan9252.gen/sources_1/bd/kd240_ecat_bd/ip/kd240_ecat_bd_axi_smc_0/bd_0/ip/ip_10/bd_6104_woutsw_0_ooc.xdc

# XDC: c:/Users/user/Desktop/KD240/01_vivado/kd240_ecat_lan9252/kd240_ecat_lan9252.gen/sources_1/bd/kd240_ecat_bd/ip/kd240_ecat_bd_axi_smc_0/bd_0/ip/ip_11/bd_6104_boutsw_0_ooc.xdc

# XDC: c:/Users/user/Desktop/KD240/01_vivado/kd240_ecat_lan9252/kd240_ecat_lan9252.gen/sources_1/bd/kd240_ecat_bd/ip/kd240_ecat_bd_axi_smc_0/bd_0/ip/ip_12/bd_6104_arni_0_ooc.xdc

# XDC: c:/Users/user/Desktop/KD240/01_vivado/kd240_ecat_lan9252/kd240_ecat_lan9252.gen/sources_1/bd/kd240_ecat_bd/ip/kd240_ecat_bd_axi_smc_0/bd_0/ip/ip_13/bd_6104_rni_0_ooc.xdc

# XDC: c:/Users/user/Desktop/KD240/01_vivado/kd240_ecat_lan9252/kd240_ecat_lan9252.gen/sources_1/bd/kd240_ecat_bd/ip/kd240_ecat_bd_axi_smc_0/bd_0/ip/ip_14/bd_6104_awni_0_ooc.xdc

# XDC: c:/Users/user/Desktop/KD240/01_vivado/kd240_ecat_lan9252/kd240_ecat_lan9252.gen/sources_1/bd/kd240_ecat_bd/ip/kd240_ecat_bd_axi_smc_0/bd_0/ip/ip_15/bd_6104_wni_0_ooc.xdc

# XDC: c:/Users/user/Desktop/KD240/01_vivado/kd240_ecat_lan9252/kd240_ecat_lan9252.gen/sources_1/bd/kd240_ecat_bd/ip/kd240_ecat_bd_axi_smc_0/bd_0/ip/ip_16/bd_6104_bni_0_ooc.xdc

# XDC: c:/Users/user/Desktop/KD240/01_vivado/kd240_ecat_lan9252/kd240_ecat_lan9252.gen/sources_1/bd/kd240_ecat_bd/ip/kd240_ecat_bd_axi_smc_0/bd_0/ip/ip_20/bd_6104_s00a2s_0_ooc.xdc

# XDC: c:/Users/user/Desktop/KD240/01_vivado/kd240_ecat_lan9252/kd240_ecat_lan9252.gen/sources_1/bd/kd240_ecat_bd/ip/kd240_ecat_bd_axi_smc_0/bd_0/ip/ip_21/bd_6104_sarn_0_ooc.xdc

# XDC: c:/Users/user/Desktop/KD240/01_vivado/kd240_ecat_lan9252/kd240_ecat_lan9252.gen/sources_1/bd/kd240_ecat_bd/ip/kd240_ecat_bd_axi_smc_0/bd_0/ip/ip_22/bd_6104_srn_0_ooc.xdc

# XDC: c:/Users/user/Desktop/KD240/01_vivado/kd240_ecat_lan9252/kd240_ecat_lan9252.gen/sources_1/bd/kd240_ecat_bd/ip/kd240_ecat_bd_axi_smc_0/bd_0/ip/ip_23/bd_6104_sawn_0_ooc.xdc

# XDC: c:/Users/user/Desktop/KD240/01_vivado/kd240_ecat_lan9252/kd240_ecat_lan9252.gen/sources_1/bd/kd240_ecat_bd/ip/kd240_ecat_bd_axi_smc_0/bd_0/ip/ip_24/bd_6104_swn_0_ooc.xdc

# XDC: c:/Users/user/Desktop/KD240/01_vivado/kd240_ecat_lan9252/kd240_ecat_lan9252.gen/sources_1/bd/kd240_ecat_bd/ip/kd240_ecat_bd_axi_smc_0/bd_0/ip/ip_25/bd_6104_sbn_0_ooc.xdc

# XDC: c:/Users/user/Desktop/KD240/01_vivado/kd240_ecat_lan9252/kd240_ecat_lan9252.gen/sources_1/bd/kd240_ecat_bd/ip/kd240_ecat_bd_axi_smc_0/bd_0/ip/ip_29/bd_6104_s01a2s_0_ooc.xdc

# XDC: c:/Users/user/Desktop/KD240/01_vivado/kd240_ecat_lan9252/kd240_ecat_lan9252.gen/sources_1/bd/kd240_ecat_bd/ip/kd240_ecat_bd_axi_smc_0/bd_0/ip/ip_30/bd_6104_sarn_1_ooc.xdc

# XDC: c:/Users/user/Desktop/KD240/01_vivado/kd240_ecat_lan9252/kd240_ecat_lan9252.gen/sources_1/bd/kd240_ecat_bd/ip/kd240_ecat_bd_axi_smc_0/bd_0/ip/ip_31/bd_6104_srn_1_ooc.xdc

# XDC: c:/Users/user/Desktop/KD240/01_vivado/kd240_ecat_lan9252/kd240_ecat_lan9252.gen/sources_1/bd/kd240_ecat_bd/ip/kd240_ecat_bd_axi_smc_0/bd_0/ip/ip_32/bd_6104_sawn_1_ooc.xdc

# XDC: c:/Users/user/Desktop/KD240/01_vivado/kd240_ecat_lan9252/kd240_ecat_lan9252.gen/sources_1/bd/kd240_ecat_bd/ip/kd240_ecat_bd_axi_smc_0/bd_0/ip/ip_33/bd_6104_swn_1_ooc.xdc

# XDC: c:/Users/user/Desktop/KD240/01_vivado/kd240_ecat_lan9252/kd240_ecat_lan9252.gen/sources_1/bd/kd240_ecat_bd/ip/kd240_ecat_bd_axi_smc_0/bd_0/ip/ip_34/bd_6104_sbn_1_ooc.xdc

# XDC: c:/Users/user/Desktop/KD240/01_vivado/kd240_ecat_lan9252/kd240_ecat_lan9252.gen/sources_1/bd/kd240_ecat_bd/ip/kd240_ecat_bd_axi_smc_0/bd_0/ip/ip_35/bd_6104_m00s2a_0_ooc.xdc

# XDC: c:/Users/user/Desktop/KD240/01_vivado/kd240_ecat_lan9252/kd240_ecat_lan9252.gen/sources_1/bd/kd240_ecat_bd/ip/kd240_ecat_bd_axi_smc_0/bd_0/ip/ip_36/bd_6104_m00arn_0_ooc.xdc

# XDC: c:/Users/user/Desktop/KD240/01_vivado/kd240_ecat_lan9252/kd240_ecat_lan9252.gen/sources_1/bd/kd240_ecat_bd/ip/kd240_ecat_bd_axi_smc_0/bd_0/ip/ip_37/bd_6104_m00rn_0_ooc.xdc

# XDC: c:/Users/user/Desktop/KD240/01_vivado/kd240_ecat_lan9252/kd240_ecat_lan9252.gen/sources_1/bd/kd240_ecat_bd/ip/kd240_ecat_bd_axi_smc_0/bd_0/ip/ip_38/bd_6104_m00awn_0_ooc.xdc

# XDC: c:/Users/user/Desktop/KD240/01_vivado/kd240_ecat_lan9252/kd240_ecat_lan9252.gen/sources_1/bd/kd240_ecat_bd/ip/kd240_ecat_bd_axi_smc_0/bd_0/ip/ip_39/bd_6104_m00wn_0_ooc.xdc

# XDC: c:/Users/user/Desktop/KD240/01_vivado/kd240_ecat_lan9252/kd240_ecat_lan9252.gen/sources_1/bd/kd240_ecat_bd/ip/kd240_ecat_bd_axi_smc_0/bd_0/ip/ip_40/bd_6104_m00bn_0_ooc.xdc

# XDC: c:/Users/user/Desktop/KD240/01_vivado/kd240_ecat_lan9252/kd240_ecat_lan9252.gen/sources_1/bd/kd240_ecat_bd/ip/kd240_ecat_bd_axi_smc_0/bd_0/ip/ip_42/bd_6104_m01s2a_0_ooc.xdc

# XDC: c:/Users/user/Desktop/KD240/01_vivado/kd240_ecat_lan9252/kd240_ecat_lan9252.gen/sources_1/bd/kd240_ecat_bd/ip/kd240_ecat_bd_axi_smc_0/bd_0/ip/ip_43/bd_6104_m01arn_0_ooc.xdc

# XDC: c:/Users/user/Desktop/KD240/01_vivado/kd240_ecat_lan9252/kd240_ecat_lan9252.gen/sources_1/bd/kd240_ecat_bd/ip/kd240_ecat_bd_axi_smc_0/bd_0/ip/ip_44/bd_6104_m01rn_0_ooc.xdc

# XDC: c:/Users/user/Desktop/KD240/01_vivado/kd240_ecat_lan9252/kd240_ecat_lan9252.gen/sources_1/bd/kd240_ecat_bd/ip/kd240_ecat_bd_axi_smc_0/bd_0/ip/ip_45/bd_6104_m01awn_0_ooc.xdc

# XDC: c:/Users/user/Desktop/KD240/01_vivado/kd240_ecat_lan9252/kd240_ecat_lan9252.gen/sources_1/bd/kd240_ecat_bd/ip/kd240_ecat_bd_axi_smc_0/bd_0/ip/ip_46/bd_6104_m01wn_0_ooc.xdc

# XDC: c:/Users/user/Desktop/KD240/01_vivado/kd240_ecat_lan9252/kd240_ecat_lan9252.gen/sources_1/bd/kd240_ecat_bd/ip/kd240_ecat_bd_axi_smc_0/bd_0/ip/ip_47/bd_6104_m01bn_0_ooc.xdc

# XDC: c:/Users/user/Desktop/KD240/01_vivado/kd240_ecat_lan9252/kd240_ecat_lan9252.gen/sources_1/bd/kd240_ecat_bd/ip/kd240_ecat_bd_axi_smc_0/bd_0/ip/ip_49/bd_6104_m02s2a_0_ooc.xdc

# XDC: c:/Users/user/Desktop/KD240/01_vivado/kd240_ecat_lan9252/kd240_ecat_lan9252.gen/sources_1/bd/kd240_ecat_bd/ip/kd240_ecat_bd_axi_smc_0/bd_0/ip/ip_50/bd_6104_m02arn_0_ooc.xdc

# XDC: c:/Users/user/Desktop/KD240/01_vivado/kd240_ecat_lan9252/kd240_ecat_lan9252.gen/sources_1/bd/kd240_ecat_bd/ip/kd240_ecat_bd_axi_smc_0/bd_0/ip/ip_51/bd_6104_m02rn_0_ooc.xdc

# XDC: c:/Users/user/Desktop/KD240/01_vivado/kd240_ecat_lan9252/kd240_ecat_lan9252.gen/sources_1/bd/kd240_ecat_bd/ip/kd240_ecat_bd_axi_smc_0/bd_0/ip/ip_52/bd_6104_m02awn_0_ooc.xdc

# XDC: c:/Users/user/Desktop/KD240/01_vivado/kd240_ecat_lan9252/kd240_ecat_lan9252.gen/sources_1/bd/kd240_ecat_bd/ip/kd240_ecat_bd_axi_smc_0/bd_0/ip/ip_53/bd_6104_m02wn_0_ooc.xdc

# XDC: c:/Users/user/Desktop/KD240/01_vivado/kd240_ecat_lan9252/kd240_ecat_lan9252.gen/sources_1/bd/kd240_ecat_bd/ip/kd240_ecat_bd_axi_smc_0/bd_0/ip/ip_54/bd_6104_m02bn_0_ooc.xdc

# XDC: c:/Users/user/Desktop/KD240/01_vivado/kd240_ecat_lan9252/kd240_ecat_lan9252.gen/sources_1/bd/kd240_ecat_bd/ip/kd240_ecat_bd_axi_smc_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'kd240_ecat_bd_axi_smc_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/user/Desktop/KD240/01_vivado/kd240_ecat_lan9252/kd240_ecat_lan9252.gen/sources_1/bd/kd240_ecat_bd/ip/kd240_ecat_bd_axi_smc_0/smartconnect.xdc
# XDC: The top module name and the constraint reference have the same name: 'kd240_ecat_bd_axi_smc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/Users/user/Desktop/KD240/01_vivado/kd240_ecat_lan9252/kd240_ecat_lan9252.srcs/sources_1/bd/kd240_ecat_bd/ip/kd240_ecat_bd_axi_smc_0/kd240_ecat_bd_axi_smc_0.xci
# IP: The module: 'kd240_ecat_bd_axi_smc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/Users/user/Desktop/KD240/01_vivado/kd240_ecat_lan9252/kd240_ecat_lan9252.gen/sources_1/bd/kd240_ecat_bd/ip/kd240_ecat_bd_axi_smc_0/bd_0/bd_6104.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/user/Desktop/KD240/01_vivado/kd240_ecat_lan9252/kd240_ecat_lan9252.gen/sources_1/bd/kd240_ecat_bd/ip/kd240_ecat_bd_axi_smc_0/bd_0/ip/ip_1/bd_6104_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/user/Desktop/KD240/01_vivado/kd240_ecat_lan9252/kd240_ecat_lan9252.gen/sources_1/bd/kd240_ecat_bd/ip/kd240_ecat_bd_axi_smc_0/bd_0/ip/ip_2/bd_6104_arinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/user/Desktop/KD240/01_vivado/kd240_ecat_lan9252/kd240_ecat_lan9252.gen/sources_1/bd/kd240_ecat_bd/ip/kd240_ecat_bd_axi_smc_0/bd_0/ip/ip_3/bd_6104_rinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/user/Desktop/KD240/01_vivado/kd240_ecat_lan9252/kd240_ecat_lan9252.gen/sources_1/bd/kd240_ecat_bd/ip/kd240_ecat_bd_axi_smc_0/bd_0/ip/ip_4/bd_6104_awinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/user/Desktop/KD240/01_vivado/kd240_ecat_lan9252/kd240_ecat_lan9252.gen/sources_1/bd/kd240_ecat_bd/ip/kd240_ecat_bd_axi_smc_0/bd_0/ip/ip_5/bd_6104_winsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/user/Desktop/KD240/01_vivado/kd240_ecat_lan9252/kd240_ecat_lan9252.gen/sources_1/bd/kd240_ecat_bd/ip/kd240_ecat_bd_axi_smc_0/bd_0/ip/ip_6/bd_6104_binsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/user/Desktop/KD240/01_vivado/kd240_ecat_lan9252/kd240_ecat_lan9252.gen/sources_1/bd/kd240_ecat_bd/ip/kd240_ecat_bd_axi_smc_0/bd_0/ip/ip_7/bd_6104_aroutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/user/Desktop/KD240/01_vivado/kd240_ecat_lan9252/kd240_ecat_lan9252.gen/sources_1/bd/kd240_ecat_bd/ip/kd240_ecat_bd_axi_smc_0/bd_0/ip/ip_8/bd_6104_routsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/user/Desktop/KD240/01_vivado/kd240_ecat_lan9252/kd240_ecat_lan9252.gen/sources_1/bd/kd240_ecat_bd/ip/kd240_ecat_bd_axi_smc_0/bd_0/ip/ip_9/bd_6104_awoutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/user/Desktop/KD240/01_vivado/kd240_ecat_lan9252/kd240_ecat_lan9252.gen/sources_1/bd/kd240_ecat_bd/ip/kd240_ecat_bd_axi_smc_0/bd_0/ip/ip_10/bd_6104_woutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/user/Desktop/KD240/01_vivado/kd240_ecat_lan9252/kd240_ecat_lan9252.gen/sources_1/bd/kd240_ecat_bd/ip/kd240_ecat_bd_axi_smc_0/bd_0/ip/ip_11/bd_6104_boutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/user/Desktop/KD240/01_vivado/kd240_ecat_lan9252/kd240_ecat_lan9252.gen/sources_1/bd/kd240_ecat_bd/ip/kd240_ecat_bd_axi_smc_0/bd_0/ip/ip_12/bd_6104_arni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/user/Desktop/KD240/01_vivado/kd240_ecat_lan9252/kd240_ecat_lan9252.gen/sources_1/bd/kd240_ecat_bd/ip/kd240_ecat_bd_axi_smc_0/bd_0/ip/ip_13/bd_6104_rni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/user/Desktop/KD240/01_vivado/kd240_ecat_lan9252/kd240_ecat_lan9252.gen/sources_1/bd/kd240_ecat_bd/ip/kd240_ecat_bd_axi_smc_0/bd_0/ip/ip_14/bd_6104_awni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/user/Desktop/KD240/01_vivado/kd240_ecat_lan9252/kd240_ecat_lan9252.gen/sources_1/bd/kd240_ecat_bd/ip/kd240_ecat_bd_axi_smc_0/bd_0/ip/ip_15/bd_6104_wni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/user/Desktop/KD240/01_vivado/kd240_ecat_lan9252/kd240_ecat_lan9252.gen/sources_1/bd/kd240_ecat_bd/ip/kd240_ecat_bd_axi_smc_0/bd_0/ip/ip_16/bd_6104_bni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/user/Desktop/KD240/01_vivado/kd240_ecat_lan9252/kd240_ecat_lan9252.gen/sources_1/bd/kd240_ecat_bd/ip/kd240_ecat_bd_axi_smc_0/bd_0/ip/ip_17/bd_6104_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/user/Desktop/KD240/01_vivado/kd240_ecat_lan9252/kd240_ecat_lan9252.gen/sources_1/bd/kd240_ecat_bd/ip/kd240_ecat_bd_axi_smc_0/bd_0/ip/ip_18/bd_6104_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/user/Desktop/KD240/01_vivado/kd240_ecat_lan9252/kd240_ecat_lan9252.gen/sources_1/bd/kd240_ecat_bd/ip/kd240_ecat_bd_axi_smc_0/bd_0/ip/ip_19/bd_6104_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/user/Desktop/KD240/01_vivado/kd240_ecat_lan9252/kd240_ecat_lan9252.gen/sources_1/bd/kd240_ecat_bd/ip/kd240_ecat_bd_axi_smc_0/bd_0/ip/ip_20/bd_6104_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/user/Desktop/KD240/01_vivado/kd240_ecat_lan9252/kd240_ecat_lan9252.gen/sources_1/bd/kd240_ecat_bd/ip/kd240_ecat_bd_axi_smc_0/bd_0/ip/ip_21/bd_6104_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/user/Desktop/KD240/01_vivado/kd240_ecat_lan9252/kd240_ecat_lan9252.gen/sources_1/bd/kd240_ecat_bd/ip/kd240_ecat_bd_axi_smc_0/bd_0/ip/ip_22/bd_6104_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/user/Desktop/KD240/01_vivado/kd240_ecat_lan9252/kd240_ecat_lan9252.gen/sources_1/bd/kd240_ecat_bd/ip/kd240_ecat_bd_axi_smc_0/bd_0/ip/ip_23/bd_6104_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/user/Desktop/KD240/01_vivado/kd240_ecat_lan9252/kd240_ecat_lan9252.gen/sources_1/bd/kd240_ecat_bd/ip/kd240_ecat_bd_axi_smc_0/bd_0/ip/ip_24/bd_6104_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/user/Desktop/KD240/01_vivado/kd240_ecat_lan9252/kd240_ecat_lan9252.gen/sources_1/bd/kd240_ecat_bd/ip/kd240_ecat_bd_axi_smc_0/bd_0/ip/ip_25/bd_6104_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/user/Desktop/KD240/01_vivado/kd240_ecat_lan9252/kd240_ecat_lan9252.gen/sources_1/bd/kd240_ecat_bd/ip/kd240_ecat_bd_axi_smc_0/bd_0/ip/ip_26/bd_6104_s01mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/user/Desktop/KD240/01_vivado/kd240_ecat_lan9252/kd240_ecat_lan9252.gen/sources_1/bd/kd240_ecat_bd/ip/kd240_ecat_bd_axi_smc_0/bd_0/ip/ip_27/bd_6104_s01tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/user/Desktop/KD240/01_vivado/kd240_ecat_lan9252/kd240_ecat_lan9252.gen/sources_1/bd/kd240_ecat_bd/ip/kd240_ecat_bd_axi_smc_0/bd_0/ip/ip_28/bd_6104_s01sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/user/Desktop/KD240/01_vivado/kd240_ecat_lan9252/kd240_ecat_lan9252.gen/sources_1/bd/kd240_ecat_bd/ip/kd240_ecat_bd_axi_smc_0/bd_0/ip/ip_29/bd_6104_s01a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/user/Desktop/KD240/01_vivado/kd240_ecat_lan9252/kd240_ecat_lan9252.gen/sources_1/bd/kd240_ecat_bd/ip/kd240_ecat_bd_axi_smc_0/bd_0/ip/ip_30/bd_6104_sarn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/user/Desktop/KD240/01_vivado/kd240_ecat_lan9252/kd240_ecat_lan9252.gen/sources_1/bd/kd240_ecat_bd/ip/kd240_ecat_bd_axi_smc_0/bd_0/ip/ip_31/bd_6104_srn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/user/Desktop/KD240/01_vivado/kd240_ecat_lan9252/kd240_ecat_lan9252.gen/sources_1/bd/kd240_ecat_bd/ip/kd240_ecat_bd_axi_smc_0/bd_0/ip/ip_32/bd_6104_sawn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/user/Desktop/KD240/01_vivado/kd240_ecat_lan9252/kd240_ecat_lan9252.gen/sources_1/bd/kd240_ecat_bd/ip/kd240_ecat_bd_axi_smc_0/bd_0/ip/ip_33/bd_6104_swn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/user/Desktop/KD240/01_vivado/kd240_ecat_lan9252/kd240_ecat_lan9252.gen/sources_1/bd/kd240_ecat_bd/ip/kd240_ecat_bd_axi_smc_0/bd_0/ip/ip_34/bd_6104_sbn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/user/Desktop/KD240/01_vivado/kd240_ecat_lan9252/kd240_ecat_lan9252.gen/sources_1/bd/kd240_ecat_bd/ip/kd240_ecat_bd_axi_smc_0/bd_0/ip/ip_35/bd_6104_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/user/Desktop/KD240/01_vivado/kd240_ecat_lan9252/kd240_ecat_lan9252.gen/sources_1/bd/kd240_ecat_bd/ip/kd240_ecat_bd_axi_smc_0/bd_0/ip/ip_36/bd_6104_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/user/Desktop/KD240/01_vivado/kd240_ecat_lan9252/kd240_ecat_lan9252.gen/sources_1/bd/kd240_ecat_bd/ip/kd240_ecat_bd_axi_smc_0/bd_0/ip/ip_37/bd_6104_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/user/Desktop/KD240/01_vivado/kd240_ecat_lan9252/kd240_ecat_lan9252.gen/sources_1/bd/kd240_ecat_bd/ip/kd240_ecat_bd_axi_smc_0/bd_0/ip/ip_38/bd_6104_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/user/Desktop/KD240/01_vivado/kd240_ecat_lan9252/kd240_ecat_lan9252.gen/sources_1/bd/kd240_ecat_bd/ip/kd240_ecat_bd_axi_smc_0/bd_0/ip/ip_39/bd_6104_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/user/Desktop/KD240/01_vivado/kd240_ecat_lan9252/kd240_ecat_lan9252.gen/sources_1/bd/kd240_ecat_bd/ip/kd240_ecat_bd_axi_smc_0/bd_0/ip/ip_40/bd_6104_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/user/Desktop/KD240/01_vivado/kd240_ecat_lan9252/kd240_ecat_lan9252.gen/sources_1/bd/kd240_ecat_bd/ip/kd240_ecat_bd_axi_smc_0/bd_0/ip/ip_41/bd_6104_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/user/Desktop/KD240/01_vivado/kd240_ecat_lan9252/kd240_ecat_lan9252.gen/sources_1/bd/kd240_ecat_bd/ip/kd240_ecat_bd_axi_smc_0/bd_0/ip/ip_42/bd_6104_m01s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/user/Desktop/KD240/01_vivado/kd240_ecat_lan9252/kd240_ecat_lan9252.gen/sources_1/bd/kd240_ecat_bd/ip/kd240_ecat_bd_axi_smc_0/bd_0/ip/ip_43/bd_6104_m01arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/user/Desktop/KD240/01_vivado/kd240_ecat_lan9252/kd240_ecat_lan9252.gen/sources_1/bd/kd240_ecat_bd/ip/kd240_ecat_bd_axi_smc_0/bd_0/ip/ip_44/bd_6104_m01rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/user/Desktop/KD240/01_vivado/kd240_ecat_lan9252/kd240_ecat_lan9252.gen/sources_1/bd/kd240_ecat_bd/ip/kd240_ecat_bd_axi_smc_0/bd_0/ip/ip_45/bd_6104_m01awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/user/Desktop/KD240/01_vivado/kd240_ecat_lan9252/kd240_ecat_lan9252.gen/sources_1/bd/kd240_ecat_bd/ip/kd240_ecat_bd_axi_smc_0/bd_0/ip/ip_46/bd_6104_m01wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/user/Desktop/KD240/01_vivado/kd240_ecat_lan9252/kd240_ecat_lan9252.gen/sources_1/bd/kd240_ecat_bd/ip/kd240_ecat_bd_axi_smc_0/bd_0/ip/ip_47/bd_6104_m01bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/user/Desktop/KD240/01_vivado/kd240_ecat_lan9252/kd240_ecat_lan9252.gen/sources_1/bd/kd240_ecat_bd/ip/kd240_ecat_bd_axi_smc_0/bd_0/ip/ip_48/bd_6104_m01e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/user/Desktop/KD240/01_vivado/kd240_ecat_lan9252/kd240_ecat_lan9252.gen/sources_1/bd/kd240_ecat_bd/ip/kd240_ecat_bd_axi_smc_0/bd_0/ip/ip_49/bd_6104_m02s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/user/Desktop/KD240/01_vivado/kd240_ecat_lan9252/kd240_ecat_lan9252.gen/sources_1/bd/kd240_ecat_bd/ip/kd240_ecat_bd_axi_smc_0/bd_0/ip/ip_50/bd_6104_m02arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/user/Desktop/KD240/01_vivado/kd240_ecat_lan9252/kd240_ecat_lan9252.gen/sources_1/bd/kd240_ecat_bd/ip/kd240_ecat_bd_axi_smc_0/bd_0/ip/ip_51/bd_6104_m02rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/user/Desktop/KD240/01_vivado/kd240_ecat_lan9252/kd240_ecat_lan9252.gen/sources_1/bd/kd240_ecat_bd/ip/kd240_ecat_bd_axi_smc_0/bd_0/ip/ip_52/bd_6104_m02awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/user/Desktop/KD240/01_vivado/kd240_ecat_lan9252/kd240_ecat_lan9252.gen/sources_1/bd/kd240_ecat_bd/ip/kd240_ecat_bd_axi_smc_0/bd_0/ip/ip_53/bd_6104_m02wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/user/Desktop/KD240/01_vivado/kd240_ecat_lan9252/kd240_ecat_lan9252.gen/sources_1/bd/kd240_ecat_bd/ip/kd240_ecat_bd_axi_smc_0/bd_0/ip/ip_54/bd_6104_m02bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/user/Desktop/KD240/01_vivado/kd240_ecat_lan9252/kd240_ecat_lan9252.gen/sources_1/bd/kd240_ecat_bd/ip/kd240_ecat_bd_axi_smc_0/bd_0/ip/ip_55/bd_6104_m02e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: c:/Users/user/Desktop/KD240/01_vivado/kd240_ecat_lan9252/kd240_ecat_lan9252.gen/sources_1/bd/kd240_ecat_bd/ip/kd240_ecat_bd_axi_smc_0/bd_0/ip/ip_1/bd_6104_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/user/Desktop/KD240/01_vivado/kd240_ecat_lan9252/kd240_ecat_lan9252.gen/sources_1/bd/kd240_ecat_bd/ip/kd240_ecat_bd_axi_smc_0/bd_0/ip/ip_2/bd_6104_arinsw_0_ooc.xdc

# XDC: c:/Users/user/Desktop/KD240/01_vivado/kd240_ecat_lan9252/kd240_ecat_lan9252.gen/sources_1/bd/kd240_ecat_bd/ip/kd240_ecat_bd_axi_smc_0/bd_0/ip/ip_3/bd_6104_rinsw_0_ooc.xdc

# XDC: c:/Users/user/Desktop/KD240/01_vivado/kd240_ecat_lan9252/kd240_ecat_lan9252.gen/sources_1/bd/kd240_ecat_bd/ip/kd240_ecat_bd_axi_smc_0/bd_0/ip/ip_4/bd_6104_awinsw_0_ooc.xdc

# XDC: c:/Users/user/Desktop/KD240/01_vivado/kd240_ecat_lan9252/kd240_ecat_lan9252.gen/sources_1/bd/kd240_ecat_bd/ip/kd240_ecat_bd_axi_smc_0/bd_0/ip/ip_5/bd_6104_winsw_0_ooc.xdc

# XDC: c:/Users/user/Desktop/KD240/01_vivado/kd240_ecat_lan9252/kd240_ecat_lan9252.gen/sources_1/bd/kd240_ecat_bd/ip/kd240_ecat_bd_axi_smc_0/bd_0/ip/ip_6/bd_6104_binsw_0_ooc.xdc

# XDC: c:/Users/user/Desktop/KD240/01_vivado/kd240_ecat_lan9252/kd240_ecat_lan9252.gen/sources_1/bd/kd240_ecat_bd/ip/kd240_ecat_bd_axi_smc_0/bd_0/ip/ip_7/bd_6104_aroutsw_0_ooc.xdc

# XDC: c:/Users/user/Desktop/KD240/01_vivado/kd240_ecat_lan9252/kd240_ecat_lan9252.gen/sources_1/bd/kd240_ecat_bd/ip/kd240_ecat_bd_axi_smc_0/bd_0/ip/ip_8/bd_6104_routsw_0_ooc.xdc

# XDC: c:/Users/user/Desktop/KD240/01_vivado/kd240_ecat_lan9252/kd240_ecat_lan9252.gen/sources_1/bd/kd240_ecat_bd/ip/kd240_ecat_bd_axi_smc_0/bd_0/ip/ip_9/bd_6104_awoutsw_0_ooc.xdc

# XDC: c:/Users/user/Desktop/KD240/01_vivado/kd240_ecat_lan9252/kd240_ecat_lan9252.gen/sources_1/bd/kd240_ecat_bd/ip/kd240_ecat_bd_axi_smc_0/bd_0/ip/ip_10/bd_6104_woutsw_0_ooc.xdc

# XDC: c:/Users/user/Desktop/KD240/01_vivado/kd240_ecat_lan9252/kd240_ecat_lan9252.gen/sources_1/bd/kd240_ecat_bd/ip/kd240_ecat_bd_axi_smc_0/bd_0/ip/ip_11/bd_6104_boutsw_0_ooc.xdc

# XDC: c:/Users/user/Desktop/KD240/01_vivado/kd240_ecat_lan9252/kd240_ecat_lan9252.gen/sources_1/bd/kd240_ecat_bd/ip/kd240_ecat_bd_axi_smc_0/bd_0/ip/ip_12/bd_6104_arni_0_ooc.xdc

# XDC: c:/Users/user/Desktop/KD240/01_vivado/kd240_ecat_lan9252/kd240_ecat_lan9252.gen/sources_1/bd/kd240_ecat_bd/ip/kd240_ecat_bd_axi_smc_0/bd_0/ip/ip_13/bd_6104_rni_0_ooc.xdc

# XDC: c:/Users/user/Desktop/KD240/01_vivado/kd240_ecat_lan9252/kd240_ecat_lan9252.gen/sources_1/bd/kd240_ecat_bd/ip/kd240_ecat_bd_axi_smc_0/bd_0/ip/ip_14/bd_6104_awni_0_ooc.xdc

# XDC: c:/Users/user/Desktop/KD240/01_vivado/kd240_ecat_lan9252/kd240_ecat_lan9252.gen/sources_1/bd/kd240_ecat_bd/ip/kd240_ecat_bd_axi_smc_0/bd_0/ip/ip_15/bd_6104_wni_0_ooc.xdc

# XDC: c:/Users/user/Desktop/KD240/01_vivado/kd240_ecat_lan9252/kd240_ecat_lan9252.gen/sources_1/bd/kd240_ecat_bd/ip/kd240_ecat_bd_axi_smc_0/bd_0/ip/ip_16/bd_6104_bni_0_ooc.xdc

# XDC: c:/Users/user/Desktop/KD240/01_vivado/kd240_ecat_lan9252/kd240_ecat_lan9252.gen/sources_1/bd/kd240_ecat_bd/ip/kd240_ecat_bd_axi_smc_0/bd_0/ip/ip_20/bd_6104_s00a2s_0_ooc.xdc

# XDC: c:/Users/user/Desktop/KD240/01_vivado/kd240_ecat_lan9252/kd240_ecat_lan9252.gen/sources_1/bd/kd240_ecat_bd/ip/kd240_ecat_bd_axi_smc_0/bd_0/ip/ip_21/bd_6104_sarn_0_ooc.xdc

# XDC: c:/Users/user/Desktop/KD240/01_vivado/kd240_ecat_lan9252/kd240_ecat_lan9252.gen/sources_1/bd/kd240_ecat_bd/ip/kd240_ecat_bd_axi_smc_0/bd_0/ip/ip_22/bd_6104_srn_0_ooc.xdc

# XDC: c:/Users/user/Desktop/KD240/01_vivado/kd240_ecat_lan9252/kd240_ecat_lan9252.gen/sources_1/bd/kd240_ecat_bd/ip/kd240_ecat_bd_axi_smc_0/bd_0/ip/ip_23/bd_6104_sawn_0_ooc.xdc

# XDC: c:/Users/user/Desktop/KD240/01_vivado/kd240_ecat_lan9252/kd240_ecat_lan9252.gen/sources_1/bd/kd240_ecat_bd/ip/kd240_ecat_bd_axi_smc_0/bd_0/ip/ip_24/bd_6104_swn_0_ooc.xdc

# XDC: c:/Users/user/Desktop/KD240/01_vivado/kd240_ecat_lan9252/kd240_ecat_lan9252.gen/sources_1/bd/kd240_ecat_bd/ip/kd240_ecat_bd_axi_smc_0/bd_0/ip/ip_25/bd_6104_sbn_0_ooc.xdc

# XDC: c:/Users/user/Desktop/KD240/01_vivado/kd240_ecat_lan9252/kd240_ecat_lan9252.gen/sources_1/bd/kd240_ecat_bd/ip/kd240_ecat_bd_axi_smc_0/bd_0/ip/ip_29/bd_6104_s01a2s_0_ooc.xdc

# XDC: c:/Users/user/Desktop/KD240/01_vivado/kd240_ecat_lan9252/kd240_ecat_lan9252.gen/sources_1/bd/kd240_ecat_bd/ip/kd240_ecat_bd_axi_smc_0/bd_0/ip/ip_30/bd_6104_sarn_1_ooc.xdc

# XDC: c:/Users/user/Desktop/KD240/01_vivado/kd240_ecat_lan9252/kd240_ecat_lan9252.gen/sources_1/bd/kd240_ecat_bd/ip/kd240_ecat_bd_axi_smc_0/bd_0/ip/ip_31/bd_6104_srn_1_ooc.xdc

# XDC: c:/Users/user/Desktop/KD240/01_vivado/kd240_ecat_lan9252/kd240_ecat_lan9252.gen/sources_1/bd/kd240_ecat_bd/ip/kd240_ecat_bd_axi_smc_0/bd_0/ip/ip_32/bd_6104_sawn_1_ooc.xdc

# XDC: c:/Users/user/Desktop/KD240/01_vivado/kd240_ecat_lan9252/kd240_ecat_lan9252.gen/sources_1/bd/kd240_ecat_bd/ip/kd240_ecat_bd_axi_smc_0/bd_0/ip/ip_33/bd_6104_swn_1_ooc.xdc

# XDC: c:/Users/user/Desktop/KD240/01_vivado/kd240_ecat_lan9252/kd240_ecat_lan9252.gen/sources_1/bd/kd240_ecat_bd/ip/kd240_ecat_bd_axi_smc_0/bd_0/ip/ip_34/bd_6104_sbn_1_ooc.xdc

# XDC: c:/Users/user/Desktop/KD240/01_vivado/kd240_ecat_lan9252/kd240_ecat_lan9252.gen/sources_1/bd/kd240_ecat_bd/ip/kd240_ecat_bd_axi_smc_0/bd_0/ip/ip_35/bd_6104_m00s2a_0_ooc.xdc

# XDC: c:/Users/user/Desktop/KD240/01_vivado/kd240_ecat_lan9252/kd240_ecat_lan9252.gen/sources_1/bd/kd240_ecat_bd/ip/kd240_ecat_bd_axi_smc_0/bd_0/ip/ip_36/bd_6104_m00arn_0_ooc.xdc

# XDC: c:/Users/user/Desktop/KD240/01_vivado/kd240_ecat_lan9252/kd240_ecat_lan9252.gen/sources_1/bd/kd240_ecat_bd/ip/kd240_ecat_bd_axi_smc_0/bd_0/ip/ip_37/bd_6104_m00rn_0_ooc.xdc

# XDC: c:/Users/user/Desktop/KD240/01_vivado/kd240_ecat_lan9252/kd240_ecat_lan9252.gen/sources_1/bd/kd240_ecat_bd/ip/kd240_ecat_bd_axi_smc_0/bd_0/ip/ip_38/bd_6104_m00awn_0_ooc.xdc

# XDC: c:/Users/user/Desktop/KD240/01_vivado/kd240_ecat_lan9252/kd240_ecat_lan9252.gen/sources_1/bd/kd240_ecat_bd/ip/kd240_ecat_bd_axi_smc_0/bd_0/ip/ip_39/bd_6104_m00wn_0_ooc.xdc

# XDC: c:/Users/user/Desktop/KD240/01_vivado/kd240_ecat_lan9252/kd240_ecat_lan9252.gen/sources_1/bd/kd240_ecat_bd/ip/kd240_ecat_bd_axi_smc_0/bd_0/ip/ip_40/bd_6104_m00bn_0_ooc.xdc

# XDC: c:/Users/user/Desktop/KD240/01_vivado/kd240_ecat_lan9252/kd240_ecat_lan9252.gen/sources_1/bd/kd240_ecat_bd/ip/kd240_ecat_bd_axi_smc_0/bd_0/ip/ip_42/bd_6104_m01s2a_0_ooc.xdc

# XDC: c:/Users/user/Desktop/KD240/01_vivado/kd240_ecat_lan9252/kd240_ecat_lan9252.gen/sources_1/bd/kd240_ecat_bd/ip/kd240_ecat_bd_axi_smc_0/bd_0/ip/ip_43/bd_6104_m01arn_0_ooc.xdc

# XDC: c:/Users/user/Desktop/KD240/01_vivado/kd240_ecat_lan9252/kd240_ecat_lan9252.gen/sources_1/bd/kd240_ecat_bd/ip/kd240_ecat_bd_axi_smc_0/bd_0/ip/ip_44/bd_6104_m01rn_0_ooc.xdc

# XDC: c:/Users/user/Desktop/KD240/01_vivado/kd240_ecat_lan9252/kd240_ecat_lan9252.gen/sources_1/bd/kd240_ecat_bd/ip/kd240_ecat_bd_axi_smc_0/bd_0/ip/ip_45/bd_6104_m01awn_0_ooc.xdc

# XDC: c:/Users/user/Desktop/KD240/01_vivado/kd240_ecat_lan9252/kd240_ecat_lan9252.gen/sources_1/bd/kd240_ecat_bd/ip/kd240_ecat_bd_axi_smc_0/bd_0/ip/ip_46/bd_6104_m01wn_0_ooc.xdc

# XDC: c:/Users/user/Desktop/KD240/01_vivado/kd240_ecat_lan9252/kd240_ecat_lan9252.gen/sources_1/bd/kd240_ecat_bd/ip/kd240_ecat_bd_axi_smc_0/bd_0/ip/ip_47/bd_6104_m01bn_0_ooc.xdc

# XDC: c:/Users/user/Desktop/KD240/01_vivado/kd240_ecat_lan9252/kd240_ecat_lan9252.gen/sources_1/bd/kd240_ecat_bd/ip/kd240_ecat_bd_axi_smc_0/bd_0/ip/ip_49/bd_6104_m02s2a_0_ooc.xdc

# XDC: c:/Users/user/Desktop/KD240/01_vivado/kd240_ecat_lan9252/kd240_ecat_lan9252.gen/sources_1/bd/kd240_ecat_bd/ip/kd240_ecat_bd_axi_smc_0/bd_0/ip/ip_50/bd_6104_m02arn_0_ooc.xdc

# XDC: c:/Users/user/Desktop/KD240/01_vivado/kd240_ecat_lan9252/kd240_ecat_lan9252.gen/sources_1/bd/kd240_ecat_bd/ip/kd240_ecat_bd_axi_smc_0/bd_0/ip/ip_51/bd_6104_m02rn_0_ooc.xdc

# XDC: c:/Users/user/Desktop/KD240/01_vivado/kd240_ecat_lan9252/kd240_ecat_lan9252.gen/sources_1/bd/kd240_ecat_bd/ip/kd240_ecat_bd_axi_smc_0/bd_0/ip/ip_52/bd_6104_m02awn_0_ooc.xdc

# XDC: c:/Users/user/Desktop/KD240/01_vivado/kd240_ecat_lan9252/kd240_ecat_lan9252.gen/sources_1/bd/kd240_ecat_bd/ip/kd240_ecat_bd_axi_smc_0/bd_0/ip/ip_53/bd_6104_m02wn_0_ooc.xdc

# XDC: c:/Users/user/Desktop/KD240/01_vivado/kd240_ecat_lan9252/kd240_ecat_lan9252.gen/sources_1/bd/kd240_ecat_bd/ip/kd240_ecat_bd_axi_smc_0/bd_0/ip/ip_54/bd_6104_m02bn_0_ooc.xdc

# XDC: c:/Users/user/Desktop/KD240/01_vivado/kd240_ecat_lan9252/kd240_ecat_lan9252.gen/sources_1/bd/kd240_ecat_bd/ip/kd240_ecat_bd_axi_smc_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'kd240_ecat_bd_axi_smc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/user/Desktop/KD240/01_vivado/kd240_ecat_lan9252/kd240_ecat_lan9252.gen/sources_1/bd/kd240_ecat_bd/ip/kd240_ecat_bd_axi_smc_0/smartconnect.xdc
# XDC: The top module name and the constraint reference have the same name: 'kd240_ecat_bd_axi_smc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
